### ISSUE TITLE
Dont detect hooks in JIT code

### ISSUE THREAD

**Issue by Symbai** [DefCon42/hookbong#2]
Works fine when something is hooked inside a module. But it does not detect hooks inside memory which is allocated and filled by just-in-time compilers, such as mono.

**Comment by H4vC** [comment]
Outside of scope, compilers (jit ones especially) aren't deterministic.

**Comment by DefCon42** [comment]
(Note: If you have a heuristic to determine whether a given read-write-execute memory region has hooks in it, given no other information, please tell us.)

**Comment by DefCon42** [comment]
The problem here is we don't really have anything we can compare the hooked code against. Unfortunately JIT compilers just generally don't give us enough information to determine whether something was hooked. 

An interesting idea would be to JIT compile the code yourself and compare against that; however, that's outside of the scope of this project due to the need for code injection. Though my reply was a bit tongue-in-cheek, I'm serious in that if you can somehow circumvent these issues and open a PR I will happy eat my words and accept it.
